### ISSUE TITLE
AWS CRT: architecture not supported: arm

### ISSUE THREAD

**Issue by MMaiero** [awslabs/aws-crt-java#153]
Hello,
I'm trying to run the SDK on a raspberry pi with openjdk 8 (1.8.0_212-8u212-b01-1+rpi1-b01) but when trying to connect the CRT class is reporting an architecture not supported exception:

```
Unable to determine platform for AWS CRT: software.amazon.awssdk.crt.CRT$UnknownPlatformException: AWS CRT: architecture not supported: arm
software.amazon.awssdk.crt.CRT$UnknownPlatformException: AWS CRT: architecture not supported: arm
	at software.amazon.awssdk.crt.CRT.getArchIdentifier(CRT.java:95)
	at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:126)
	at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:38)
	at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:99)
```

It seems to be related to the fact that the JVM for the os.arch property is reporting just "arm" and that makes the code to fail https://github.com/awslabs/aws-crt-java/blob/master/src/main/java/software/amazon/awssdk/crt/CRT.java#L81

**Comment by rccarper** [comment]
Hello,

I've created a branch with a possible fix for your issue: https://github.com/awslabs/aws-crt-java/tree/raspberry_pi_arm_fix.  Basically, it just adds an additional else-if to the getArchIdentifier method that should cover your use case.  Are you getting the CRT via Maven?  (If so, we can push a new build with the change.)

Thanks,
Ryan

**Comment by MMaiero** [comment]
Hi,
Thank you for the fix!
Yes, I’m fetching it via Maven.

Best regards,
Matteo

**Comment by rccarper** [comment]
Hey Matteo,

Version 0.4.20 has the potential fix, and should now be accessible through Maven.

Thanks,
Ryan

**Comment by MMaiero** [comment]
Hi @rccarper,
the fix works and it is correctly trying to load the proper library.
The real problem now is that there are no available libs for arm v7.
In my case, then, the code fails with the following message:
```
Unable to unpack AWS CRT lib: java.io.IOException: Unable to open library in jar for AWS CRT: /linux/armv7/libaws-crt-jni.so
java.io.IOException: Unable to open library in jar for AWS CRT: /linux/armv7/libaws-crt-jni.so
	at software.amazon.awssdk.crt.CRT.loadLibraryFromJar(CRT.java:134)
	at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:38)
	at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:99)
```

Any plan in supporting that architecture?
I see that the same problem can arise now with arm v6 and aarch64: the code will be able to load the proper.so library, but that will be actually not there.

**Comment by rccarper** [comment]
Hey,

Sorry that you are running into that error now!  We are investigating adding arm v7 support.  Once I have another update, I'll respond to this issue.

Thanks,
Ryan

**Comment by rccarper** [comment]
Just pinging this thread to let you know that we haven't forgotten about it.  We are still investigating adding support for arm v7.

**Comment by MMaiero** [comment]
Thank you for the feedback

**Comment by MMaiero** [comment]
Hi @rccarper, 
any update on this topic?
Best regards,
Matteo

**Comment by rccarper** [comment]
We have someone that has been working on it, and we are hopeful that it will be done in the next few days.

**Comment by MMaiero** [comment]
Hi @justinboswell,
thank you for the update.
After the update of the library, I'm now getting the following exception:

```
Caused by: software.amazon.awssdk.crt.CrtRuntimeException: Invalid ClientBootstrap (aws_last_error: AWS_ERROR_SUCCESS(0), Success.)
	at software.amazon.awssdk.crt.mqtt.MqttClient.mqttClientNew(Native Method)
	at software.amazon.awssdk.crt.mqtt.MqttClient.<init>(MqttClient.java:51)
	at software.amazon.awssdk.iot.AwsIotMqttConnectionBuilder.build(AwsIotMqttConnectionBuilder.java:418)
```

It seems like the clientbootstrap is not set even if, following the examples, my code seems to do that as you can see in the following snippet. 

```
try (EventLoopGroup elg = new EventLoopGroup(1);
                HostResolver hr = new HostResolver(elg);
                ClientBootstrap bootstrap = new ClientBootstrap(elg, hr);
                AwsIotMqttConnectionBuilder builder = AwsIotMqttConnectionBuilder.newMtlsBuilder(pemCertificate,
                        new String(pemPrivateKey))) {

            pemPrivateKey = null;

            logger.info("Client initialized with TLS context...");
            builder.withBootstrap(bootstrap).withConnectionEventCallbacks(callbacks).withClientId(this.clientId)
                    .withEndpoint(this.clientEndpoint).withCleanSession(true)
                    .withCertificateAuthority(pemCaRootCertificate);

            return builder;
        }
```
Any clue?

Best regards,
Matteo

**Comment by bretambrose** [comment]
Many Java types in the CRT are thin wrappers around dynamically-allocated native types; these native types wrap threads, sockets, and of course memory.  Additionally, there are clean-up dependencies between these types - if not cleaned up in the right order, you'll get difficult-to-debug native-code crashes.

To try and address this, we added ref counting to the relevant CRT types.  Java doesn't support user-implemented ref-counting very well and so what you're seeing is the sharp edge associated with that.

We implemented ref-counting by derivation from a base class: CrtResource.  There are two kinds of types that are ref-counted in the CRT:
1. Types that wrap one or more native objects. Examples in your snippet include EventLoopGroup, HostResolver, and ClientBootstrap
1. Types that do not wrap a native object but do hold onto other ref-counted types.  An example in your snippet is AwsIotMqttConnectionBuilder.

We use try-with-resources as a (very weak) ref-count-leak-protect mechanism.  The ref count rules are as follows.

A CrtResource gets a ref count increment when
1. It's created
1. Another CrtResource declares a destruction dependency on it.  For example, the dependencies of a ClientBootstrap (HostResolver, EventLoopGroup) must not be cleaned up until after the ClientBootstrap has been cleaned up (example: https://github.com/awslabs/aws-crt-java/blob/master/src/main/java/software/amazon/awssdk/crt/io/ClientBootstrap.java#L37)
1. The user calls CrtResource.addRef() (https://github.com/awslabs/aws-crt-java/blob/master/src/main/java/software/amazon/awssdk/crt/CrtResource.java#L221)

CrtResources implement the AutoCloseable interface.  A CrtResource gets its reference count decremented when close() gets called on it.  So the ref count decreases when:
1.  A try-with-resources block will automatically get a reference decrement when that block is exited.
1. When a CrtResource is fully cleaned up it will decrement the ref count of all its dependent resources (https://github.com/awslabs/aws-crt-java/blob/master/src/main/java/software/amazon/awssdk/crt/CrtResource.java#L287).

Note that you can also manually call close() yourself.

With that background out of the way, we can look at your snippet and guess at what's happening.  The step-by-step ref count details aren't interesting (unless you're debugging it), but in summary, you create a bunch of objects, ref counts get made between them, but when you hit the return statement (and exit the try-with-resources block), they all get completely unwound.  Starting with builder, the ref counts in sequence hit zero, and the native objects get released and nulled out.  At the same time, the Java objects are still alive but now no longer reference a valid implementation.

In the short-term, there are a couple of ways to fix this (we strongly recommend the first way):

1.  Manually increment the ref count of CrtResource "root" (dependency-wise) objects that you want to escape a try-with-resources block.  In this case, all you need to do is call addRef() on the builder before returning.
1. Move the creation of "root" object out of the try-with-resources header and into the block itself.  Since the root no longer gets close() called on it, everything stays alive.

In both cases, you are now responsible for calling close() yourself when you are done with it.

If your reaction to this explanation is "This is terrible.  You should never have to care about internal ref-counting in someone else's library when using Java." you are absolutely correct.  This is a bad user experience.  The (semi-) good news is that we are planning a release in the next month or two which will completely erase the need to worry about the ref counts of CrtResource objects ever again (at the cost of a little performance, background Janitor thread(s)).  In the meantime, though, you will have to be careful with ref counts or drop the try-with-resources approach (dangerous, very application-specific as to whether or not the resulting leaks and exception vulnerability is acceptable).

**Comment by MMaiero** [comment]
Thank you
