### ISSUE TITLE
Proposed changes to the API

### ISSUE THREAD

**Issue by jonyt** [awslabs/aws-crt-java#256]
1. The method `MqttClientConnection#publish` should throw an exception if the message size exceeds 128kb, which is over the allowed limit. Currently it will silently fail. Not the expected behavior when it can't fulfill its function.
1. The method `MqttClientConnection#connect` will hang if there was an authentication error. The CRT log will have some details, although not super helpful ones (things like error 1051, or error 1049). A better to handle this would've been to throw an exception in case of failure with a detailed description of the cause.

**Comment by bretambrose** [comment]
1. Is a bit of a non-starter since we want the CRT to not be tied to AWS IoT and its limits.  Even if it were, those limits are dynamic and may grow in time, independent of the SDK.  In general, AWS SDKs tend to not enforce that kind of limit because an old SDK against a new  service may lead to a bad experience.
2. This is definitely a place we could improve on.  Is this websocket only or does this include tls mismatches (bad configuration there)?

**Comment by bretambrose** [comment]
Lacking specific repro on (2), closing.
