### ISSUE TITLE
deadlock in class initialization of CRT and CrtResource

### ISSUE THREAD

**Issue by steven-aerts** [awslabs/aws-crt-java#668]
### Describe the bug

In our production code, we have a metrics thread which calls the `CRT` class for things like `CRT#getPlatformImpl` or `CRT#nativeMemory`, while other threads are using the crt library which heavily depends on the `CrtResource`.
During class initialization we are sporadically hitting a deadlock where a thread initializes `CRT` while another one is initializing `CrtResource`.  

Both threads end up waiting for each other, which is clearly visible in the detailed stack dumps:
```
"thread-3" #23 prio=5 os_prio=0 cpu=68.51ms elapsed=2834.21s tid=0x00007f19cc0bec10 nid=0xcbce7 in Object.wait()  [0x00007f19d2ffc000]
   java.lang.Thread.State: RUNNABLE
        at software.amazon.awssdk.crt.CRT.awsCrtInit(Native Method)
        - waiting on the Class initialization monitor for software.amazon.awssdk.crt.CrtResource
        at software.amazon.awssdk.crt.CRT.<clinit>(CRT.java:46)
       ...
"thread-1" #21 prio=5 os_prio=0 cpu=143.28ms elapsed=2834.35s tid=0x00007f19c80d5d10 nid=0xcbce5 in Object.wait()  [0x00007f1a2022a000]
   java.lang.Thread.State: RUNNABLE
        at software.amazon.awssdk.crt.CrtResource.<clinit>(CrtResource.java:104)
        - waiting on the Class initialization monitor for software.amazon.awssdk.crt.CRT
        at software.amazon.awssdk.http.crt.AwsCrtAsyncHttpClient.<init>(AwsCrtAsyncHttpClient.java:96)
        at software.amazon.awssdk.http.crt.AwsCrtAsyncHttpClient.<init>(AwsCrtAsyncHttpClient.java:72)
        at software.amazon.awssdk.http.crt.AwsCrtAsyncHttpClient$DefaultBuilder.build(AwsCrtAsyncHttpClient.java:393)
        at software.amazon.awssdk.http.crt.AwsCrtAsyncHttpClient.create(AwsCrtAsyncHttpClient.java:141)
        ...
```

### Expected Behavior

That those classes can be loaded independently from each other.

### Current Behavior

Class initialisation deadlock.

### Reproduction Steps

You can reproduce this problem reliably with the following code snippet, you hit the problem typically already in the first few iterations:

```java
var classPath = Arrays.stream(System.getProperty("java.class.path").split(":")).map(file -> {
    try {
        return new File(file).toURI().toURL();
    } catch (MalformedURLException e) {
        throw new RuntimeException(e);
    }
}).toArray(URL[]::new);
for (int i = 0; i < 10; i++) {
    try(var classLoader = new URLClassLoader(classPath)) {
        new Thread(() -> {
            try {
                Class.forName("software.amazon.awssdk.crt.CRT", true, classLoader);
            } catch (ClassNotFoundException e) {
                throw new RuntimeException(e);
            }
        }).start();
        Class.forName("software.amazon.awssdk.crt.CrtResource", true, classLoader);
    }
    System.out.printf("step: %d%n", i);
}
```

### Possible Solution

Remove cyclic class initialization dependency?

### aws-crt-java version used

0.22.2 (production) and validated on main

### Java version used

17

### Operating System and version

ubuntu 20.04 linux

**Comment by bretambrose** [comment]
There is indeed a circular dependency if you are triggering the CRT class static initialization and CrtResource static initialization at the same time.  CRT static initialize includes a call into native which caches all the JNI ids used by the native code, which includes ids from CrtResource.  Attempting to get the JNI ids for CrtResource deadlocks inside the JVM implementation since someone else (the other thread, which is waiting on CRT static init) already started CrtResource static initialization.

The only workaround at the moment is to refactor your initialization to initialize the CRT once before any usages.  I realize this may not be possible because initialization order can be difficult or impossible to control in a complex application.

We're currently throwing around some solution possibilities, but none of them are satisfactory as of yet.

**Comment by steven-aerts** [comment]
I hereby confirm that #670 fixes this issue.

**Comment by bretambrose** [comment]
I need to move the internal ticket for this over to the Java SDK team so that they know to take the new version, and that should finish things up.
